// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: core/eventer/v1/events.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SaveFailed with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SaveFailed) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SaveFailed with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SaveFailedMultiError, or
// nil if none found.
func (m *SaveFailed) ValidateAll() error {
	return m.validate(true)
}

func (m *SaveFailed) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetEvent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SaveFailedValidationError{
					field:  "Event",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SaveFailedValidationError{
					field:  "Event",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEvent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SaveFailedValidationError{
				field:  "Event",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Error

	if all {
		switch v := interface{}(m.GetReceivedTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SaveFailedValidationError{
					field:  "ReceivedTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SaveFailedValidationError{
					field:  "ReceivedTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetReceivedTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SaveFailedValidationError{
				field:  "ReceivedTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetPublishedTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SaveFailedValidationError{
					field:  "PublishedTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SaveFailedValidationError{
					field:  "PublishedTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPublishedTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SaveFailedValidationError{
				field:  "PublishedTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SaveFailedMultiError(errors)
	}

	return nil
}

// SaveFailedMultiError is an error wrapping multiple validation errors
// returned by SaveFailed.ValidateAll() if the designated constraints aren't met.
type SaveFailedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SaveFailedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SaveFailedMultiError) AllErrors() []error { return m }

// SaveFailedValidationError is the validation error returned by
// SaveFailed.Validate if the designated constraints aren't met.
type SaveFailedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SaveFailedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SaveFailedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SaveFailedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SaveFailedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SaveFailedValidationError) ErrorName() string { return "SaveFailedValidationError" }

// Error satisfies the builtin error interface
func (e SaveFailedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSaveFailed.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SaveFailedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SaveFailedValidationError{}
