// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: domain1/aggregate1/v1/events.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Created with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Created) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Created with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in CreatedMultiError, or nil if none found.
func (m *Created) ValidateAll() error {
	return m.validate(true)
}

func (m *Created) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return CreatedMultiError(errors)
	}

	return nil
}

// CreatedMultiError is an error wrapping multiple validation errors returned
// by Created.ValidateAll() if the designated constraints aren't met.
type CreatedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreatedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreatedMultiError) AllErrors() []error { return m }

// CreatedValidationError is the validation error returned by Created.Validate
// if the designated constraints aren't met.
type CreatedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreatedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreatedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreatedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreatedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreatedValidationError) ErrorName() string { return "CreatedValidationError" }

// Error satisfies the builtin error interface
func (e CreatedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreated.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreatedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreatedValidationError{}

// Validate checks the field values on Updated with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Updated) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Updated with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in UpdatedMultiError, or nil if none found.
func (m *Updated) ValidateAll() error {
	return m.validate(true)
}

func (m *Updated) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return UpdatedMultiError(errors)
	}

	return nil
}

// UpdatedMultiError is an error wrapping multiple validation errors returned
// by Updated.ValidateAll() if the designated constraints aren't met.
type UpdatedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdatedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdatedMultiError) AllErrors() []error { return m }

// UpdatedValidationError is the validation error returned by Updated.Validate
// if the designated constraints aren't met.
type UpdatedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdatedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdatedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdatedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdatedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdatedValidationError) ErrorName() string { return "UpdatedValidationError" }

// Error satisfies the builtin error interface
func (e UpdatedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdated.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdatedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdatedValidationError{}
